language: node_js
node_js:
    - "8"

language: node_js
dist: trusty
addons:
  apt:
    packages:
      - libnss3 # This is required to run new chrome on old trusty
cache:
  directories:
    - node_modules
